version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.jchelloworld.integrations:helloWorld
  packages:
  - name: EdgeJcHelloWorld
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.560
packages:
- name: EdgeJcHelloWorld
  gitServerName: johnpcarter
  gitUrl: https://github.com/johnpcarter/EdgeJcHelloWorld
  gitUsername: johnpcarter
  gitToken: edge.scaffolding.EdgeJcHelloWorld.johnpcarter.gitToken
  gitBranch: main
